services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - vaultwarden_data:/data
    env_file:
      - .env
    networks:
      - frontend

volumes:
  vaultwarden_data:

networks:
  frontend:
    external: true
